# Development environment override
services:
  phpredisadmin:
    image: 'mspserver-phpredisadmin-dev'
    build:
      context: .
      target: phpredisadmin_base
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    links:
      - redis
    ports:
      - "8001:80"
    networks:
      - redis

  adminer:
    image: 'mspserver-adminer-dev'
    build:
      context: .
      target: adminer_base
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_PLUGINS: 'sql-log'
      APP_ENV: ${APP_ENV:-dev}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-}
    ports:
      # run Adminer on port 8082 since 8080 will be used by mitmproxy
      - 8082:8080
    networks:
      - database
    volumes:
      - ./docker/adminer/index.php:/var/www/html/index.php:ro

  mitmproxy:
    image: 'mspserver-mitmproxy-dev'
    build:
      context: .
      target: mitmproxy_base
    container_name: mitmproxy
    entrypoint: "mitmweb --web-host 0.0.0.0 --mode reverse:http://php --set websocket=true"
    networks:
      - php
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on:
      - php

  php:
    image: 'mspserver-php-dev'
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      - /app/vendor
    networks:
      - mitmproxy
    environment:
      # this forces non-ssl
      SERVER_NAME: :80
      MERCURE_EXTRA_DIRECTIVES: demo
      # force web(socket) server over 8080 (mitmproxy reverse proxy)
      WEB_SERVER_HOST: mitmproxy
      URL_WEB_SERVER_HOST: mitmproxy
      URL_WS_SERVER_HOST: mitmproxy
      WEB_SERVER_PORT: 8080
      URL_WEB_SERVER_PORT: 8080
      URL_WS_SERVER_PORT: 8080

      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    # on dev the internal and external web server port need to match because of mitmproxy reserve proxy
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

networks:
  mitmproxy:
