server_manager_index:
    path: /
    controller: App\Controller\ServerManager\LegacyController
    defaults:
      script: 'index.php'

server_manager_script:
    path: /{script}
    controller: App\Controller\ServerManager\LegacyController
    requirements:
        script: '.+\.php'

server_manager_not_found:
  path: '/{anything}'
  controller: App\Controller\ServerManager\LegacyController::notFound
  requirements:
    anything: '.*'
