blank_issues_enabled: false
contact_links:
  - name: MSP Challenge user community wiki
    url: https://community.mspchallenge.info
    about: It gives you all the information, documentation and support you need to understand, install, use and communicate about the MSP Challenge simulation platform
