# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  # URL to the MSP Challenge download page
  app.clients_url: 'https://community.mspchallenge.info/wiki/Download'
  # directory to store and from which to retrieve game session raster files
  app.session_raster_dir: '%kernel.project_dir%/raster/'
  # directory to store and from which to retrieve a game session's configuration after its creation
  app.session_config_dir: '%kernel.project_dir%/running_session_config/'
  # format of the filename of a game session's configuration file after its creation
  app.session_config_name: 'session_config_%d.json'
  # directory to store and from which to retrieve configuration files used for session creation
  app.server_manager_config_dir: '%kernel.project_dir%/ServerManager/configfiles/'
  # minimal number of months that make up each of a game session's four eras
  # number of seconds between automatic game session database file dumps (as backup of a game session's state)
  app.game_auto_save_interval: 120
  app.min_game_era_time: 12
  # test environment specific directories, when relevant
  app.session_raster_dir_test: '%kernel.logs_dir%/raster/'
  app.session_config_dir_test: '%kernel.logs_dir%/running_session_config/'
