security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        local_users:
            entity:
                class: 'App\Entity\ServerManager\User'
                property: 'username'
        jwt:
            lexik_jwt:
                class: App\Domain\API\v1\User
    firewalls:
        # activate different ways to authenticate
        # https://symfony.com/doc/current/security.html#the-firewall
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/\d+/api/User/RequestSession$
            stateless: true
            json_login:
                check_path: session_api_user_controller
            provider: jwt
        api:
            pattern: ^/\d+/api/\w+/\w+
            stateless: true
            jwt: ~
            provider: jwt
        manager_gamelist:
            pattern: ^/manager/gamelist
            security: false
        manager:
            pattern: ^/manager
            provider: local_users
            lazy: true
            custom_authenticators:
                - App\Security\MSPAuth2Authenticator

    access_control:
        - { path: ^/\d+/api/(User/RequestToken|User/RequestSession|GameSession/\w+|Plan/ExportPlansToJson|Simulations/GetWatchdogTokenForServer|User/getProviders|User/checkExists|Game/State|Game/StartWatchdog|Game/Config|Layer/MetaByName|Game/CreatePOVConfig), roles: PUBLIC_ACCESS }
        - { path: ^/\d+/api/\w+/\w+$, roles: IS_AUTHENTICATED_FULLY }
