{
 "title": "MSP Challenge session monitoring dashboard",
 "time": { "from": "2017-12-31T23:00:00.000Z", "to": "2029-12-31T23:00:00.000Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DataSourceInstance", "query": "mysql" },
   {
    "name": "Team",
    "label": "Country",
    "query": "select country_name from country where country_is_manager = 0"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of users per country",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time_sec,\r\n  c.country_name as metric,\r\n  COUNT(u.user_id) as value\r\nFROM user u\r\ninner join country c on u.user_country_id=c.country_id \r\nwhere c.country_is_manager=0 and c.country_name is not null and u.user_loggedoff=0 and u.user_name is not null\r\n  and u.user_lastupdate >\r\n    -- timestamp of today at 00.00\r\n    UNIX_TIMESTAMP(NOW(6)) - TIME_TO_SEC(\r\n      TIMEDIFF(\r\n        TIME(NOW()),'00:00:00'\r\n      )\r\n    )\r\ngroup by c.country_name"
    }
   ]
  },
  {
   "title": "Number of plans per state",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time_sec,\r\n  plan_state as metric,\r\n  COUNT(plan_id) as value\r\nFROM plan p\r\ninner join country c on c.country_id = p.plan_country_id\r\nwhere c.country_name IN ($Team) and p.plan_state != 'DELETED'\r\nGROUP by plan_state"
    }
   ]
  },
  {
   "title": "Energy distribution overview",
   "type": "table",
   "gridPos": { "h": 15, "w": 13, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "with\n  ConnectionGeometry AS (\n    select g.geometry_id, IF(g.geometry_data='{}','{\"NumberCables\":\"1\"}',g.geometry_data) as geometry_data \n    from geometry g\n    inner join energy_connection ec on ec.energy_connection_cable_id=g.geometry_id and ec.energy_connection_active=1\n    where g.geometry_active=1\n  )\nselect\nc.country_name as Country,\nCONCAT(p.plan_name, ' farm #',g.geometry_id) as Farm,\neo.energy_output_maxcapacity/1000000000 as 'Max capacity GW',\nIFNULL(SUM(eo2.energy_output_maxcapacity),0)/1000000000 as 'Cables GW',\nSUM(IF(JSON_CONTAINS_PATH(g2.geometry_data, 'one', '$.NumberCables'),JSON_EXTRACT(g2.geometry_data, '$.NumberCables')+0,0)) as 'Number of cables',\nCONCAT(GROUP_CONCAT((eo2.energy_output_maxcapacity/1000000000) SEPARATOR ' + ')) as 'Cable GW distribution'\nfrom geometry g\ninner join layer l on l.layer_id=g.geometry_layer_id and l.layer_original_id is NOT NULL\ninner join layer ol on l.layer_original_id=ol.layer_id AND ol.layer_editing_type IN ('sourcepolygon','multitypesourcepolygon')\ninner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\ninner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state != 'DELETED'\ninner join country c on c.country_id=p.plan_country_id\ninner join energy_output eo on g.geometry_id=eo.energy_output_geometry_id\nleft join energy_connection ec on (ec.energy_connection_start_id=g.geometry_id OR ec.energy_connection_end_id=g.geometry_id) AND ec.energy_connection_active=1\nleft join ConnectionGeometry g2 on g2.geometry_id=ec.energy_connection_cable_id\nleft join energy_output eo2 on eo2.energy_output_geometry_id=g2.geometry_id\nwhere c.country_name IN ($Team) AND g.geometry_active=1\ngroup by g.geometry_id\norder by FIELD(p.plan_state,'DESIGN','CONSULTATION','APPROVAL','APPROVED','IMPLEMENTED'), p.plan_id DESC"
    }
   ]
  },
  {
   "title": "Number of energy farms",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(g.geometry_id)\r\nfrom geometry g\r\ninner join layer l on l.layer_id=g.geometry_layer_id and l.layer_original_id is NOT NULL\r\ninner join layer ol on l.layer_original_id=ol.layer_id AND ol.layer_editing_type IN ('sourcepolygon','multitypesourcepolygon')\r\ninner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\r\ninner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state != 'DELETED'\r\ninner join country c on c.country_id=p.plan_country_id\r\nwhere c.country_name IN ($Team) and g.geometry_active=1"
    }
   ]
  },
  {
   "title": "Total max. capacity GW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  IFNULL(sum(eo.energy_output_maxcapacity),0)/1000000000\r\nfrom energy_output eo\r\ninner join geometry g on g.geometry_id=eo.energy_output_geometry_id\r\ninner join layer l on l.layer_id=g.geometry_layer_id and l.layer_original_id is NOT NULL\r\ninner join layer ol on l.layer_original_id=ol.layer_id AND ol.layer_editing_type IN ('sourcepolygon','multitypesourcepolygon')\r\ninner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\r\ninner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state NOT IN('DELETED', 'ARCHIVED')\r\ninner join country c on c.country_id=p.plan_country_id\r\nwhere c.country_name IN ($Team)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select CONCAT(c.country_name, ':', u.user_name, ' (', u.user_id ,')')  as name\r\nfrom user u\r\ninner join country c on c.country_id=u.user_country_id\r\nwhere c.country_is_manager=0 and c.country_name is not null and u.user_loggedoff=0 and u.user_name is not null\r\n  and u.user_lastupdate >\r\n    -- timestamp of today at 00.00\r\n    UNIX_TIMESTAMP(NOW(6)) - TIME_TO_SEC(\r\n      TIMEDIFF(\r\n        TIME(NOW()),'00:00:00'\r\n      )\r\n    )\r\n  and c.country_name IN ($Team)\r\ngroup by u.user_id\r\norder by u.user_id DESC"
    }
   ]
  },
  {
   "title": "Total  cables GW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  IFNULL(SUM(eo2.energy_output_maxcapacity),0)/1000000000\r\nfrom geometry g\r\ninner join layer l on l.layer_id=g.geometry_layer_id and l.layer_original_id is NOT NULL\r\ninner join layer ol on l.layer_original_id=ol.layer_id AND ol.layer_editing_type IN ('sourcepolygon','multitypesourcepolygon')\r\ninner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\r\ninner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state NOT IN ('DELETED', 'ARCHIVED')\r\ninner join country c on c.country_id=p.plan_country_id\r\ninner join energy_output eo on g.geometry_id=eo.energy_output_geometry_id\r\nleft join energy_connection ec on ec.energy_connection_start_id=g.geometry_id OR ec.energy_connection_end_id=g.geometry_id\r\nleft join geometry g2 on g2.geometry_id=ec.energy_connection_cable_id and g2.geometry_active=1\r\nleft join energy_output eo2 on eo2.energy_output_geometry_id=g2.geometry_id\r\nwhere c.country_name IN ($Team) and g.geometry_active=1"
    }
   ]
  },
  {
   "title": "Plan duration until approved TODAY",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 3, "y": 10 },
   "targets": [
    {
     "rawSql": "select\r\n  CONCAT(c.country_name, ':', IF(plan_name='',CONCAT('plan ', plan_id),plan_name)) as name,\r\n  plan_state as state,\r\n  TIMEDIFF(now(), plan_time) as lifetime\r\nfrom plan p\r\ninner join country c on c.country_id = p.plan_country_id\r\nwhere plan_state IN ('DESIGN','CONSULTATION','APPROVAL') and TIMESTAMPDIFF(DAY, plan_time, now()) = 0 and c.country_name IN ($Team)\r\nORDER BY plan_time"
    }
   ]
  },
  {
   "title": "Total  missing capacity GW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT IFNULL(SUM(i.max_gw)-SUM(least(i.max_gw,i.cables_gw)),0)/1000000000 as missing_gw\r\nfrom\r\n(\r\n  SELECT\r\n    eo.energy_output_maxcapacity as max_gw,IFNULL(SUM(eo2.energy_output_maxcapacity),0) as cables_gw\r\n  from geometry g\r\n  inner join layer l on l.layer_id=g.geometry_layer_id and l.layer_original_id is NOT NULL\r\n  inner join layer ol on l.layer_original_id=ol.layer_id AND ol.layer_editing_type IN ('sourcepolygon','multitypesourcepolygon')\r\n  inner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\r\n  inner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state != 'DELETED'\r\n  inner join country c on c.country_id=p.plan_country_id\r\n  inner join energy_output eo on g.geometry_id=eo.energy_output_geometry_id\r\n  left join energy_connection ec on ec.energy_connection_start_id=g.geometry_id OR ec.energy_connection_end_id=g.geometry_id\r\n  left join geometry g2 on g2.geometry_id=ec.energy_connection_cable_id and g2.geometry_active=1\r\n  left join energy_output eo2 on eo2.energy_output_geometry_id=g2.geometry_id\r\n  where c.country_name IN ($Team) and g.geometry_active=1\r\n  group by g.geometry_id\r\n) as i"
    }
   ]
  },
  {
   "title": "Total used capacity GW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  IFNULL(sum(eo.energy_output_capacity),0)/1000000000\r\nfrom energy_output eo\r\ninner join geometry g on g.geometry_id=eo.energy_output_geometry_id\r\ninner join layer l on l.layer_id=g.geometry_layer_id and l.layer_original_id is NOT NULL\r\ninner join layer ol on l.layer_original_id=ol.layer_id AND ol.layer_editing_type IN ('sourcepolygon','multitypesourcepolygon')\r\ninner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\r\ninner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state = 'IMPLEMENTED'\r\ninner join country c on c.country_id=p.plan_country_id\r\nwhere c.country_name IN ($Team)"
    }
   ]
  },
  {
   "title": "Biomass change relative to starting value",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  -- how to detect starting year? hard-coded to 2018...\r\n  UNIX_TIMESTAMP(\r\n    CONCAT(\r\n      -- note that we merge setup month with first month\r\n      2018+FLOOR(if(k.kpi_month=-1,0,k.kpi_month)/12),\r\n      '-',\r\n      (if(k.kpi_month=-1,0,k.kpi_month) % 12)+1,\r\n      '-1 00:00:00'\r\n    )\r\n  ) as time,\r\n  CONCAT(k.kpi_name,' | ', ks.starting_value) as metric,\r\n  k.kpi_value-ks.starting_value as value\r\nFROM kpi k\r\ninner join\r\n  (\r\n    select kpi_name, kpi_country_id, kpi_value as starting_value from kpi\r\n      where kpi_type='ECOLOGY' and kpi_month=-1\r\n  ) ks on ks.kpi_name=k.kpi_name and ks.kpi_country_id=k.kpi_country_id\r\nWHERE\r\n  kpi_type='ECOLOGY'\r\n-- note that we merge setup month with first month\r\ngroup by k.kpi_name, k.kpi_country_id, IF(k.kpi_month=-1,0,k.kpi_month)\r\norder by kpi_month"
    }
   ]
  },
  {
   "title": "Number of errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(w.warning_id)\r\n from warning w\r\ninner join layer l on w.warning_layer_id=l.layer_id\r\ninner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\r\ninner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state != 'DELETED'\r\ninner join country c on c.country_id=p.plan_country_id\r\nwhere w.warning_active=1 and warning_issue_type='Error' and c.country_name IN ($Team)"
    }
   ]
  },
  {
   "title": "Old unapproved plans BEFORE TODAY",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 20 },
   "targets": [
    {
     "rawSql": "select\r\n  CONCAT(c.country_name, ':', IF(plan_name='',CONCAT('plan id: ', plan_id),plan_name)) as name,\r\n  plan_state as state,\r\n  TIMEDIFF(now(), plan_time) as lifetime\r\nfrom plan p\r\ninner join country c on c.country_id = p.plan_country_id\r\nwhere plan_state IN ('DESIGN','CONSULTATION','APPROVAL') and TIMESTAMPDIFF(DAY, plan_time, now()) > 0 and c.country_name IN ($Team)\r\nORDER BY plan_time"
    }
   ]
  },
  {
   "title": "Shipping intensity change relative to starting value",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  -- how to detect starting year? hard-coded to 2018...\r\n  UNIX_TIMESTAMP(\r\n    CONCAT(\r\n      -- note that we merge setup month with first month\r\n      2018+FLOOR(if(k.kpi_month=-1,0,k.kpi_month)/12),\r\n      '-',\r\n      (if(k.kpi_month=-1,0,k.kpi_month) % 12)+1,\r\n      '-1 00:00:00'\r\n    )\r\n  ) as time,\r\n  CONCAT(k.kpi_name,' | ', ks.starting_value) as metric,\r\n  k.kpi_value-ks.starting_value as value\r\nFROM kpi k\r\ninner join\r\n  (\r\n    select kpi_name, kpi_country_id, kpi_value as starting_value from kpi\r\n      where kpi_type='SHIPPING' and kpi_month=-1\r\n  ) ks on ks.kpi_name=k.kpi_name and ks.kpi_country_id=k.kpi_country_id\r\ninner join\r\n  (\r\n    select kpi_name, kpi_country_id, MAX(kpi_value) as max_value, MIN(kpi_value) as min_value from kpi\r\n      where kpi_type='SHIPPING' group by kpi_name, kpi_country_id\r\n  ) km on km.kpi_name=k.kpi_name and km.kpi_country_id=k.kpi_country_id\r\nWHERE\r\n  kpi_type='SHIPPING' and kpi_unit='%' and (ABS(ks.starting_value-km.max_value)>0.0001 or ABS(ks.starting_value-km.min_value)>0.0001) \r\n-- note that we merge setup month with first month\r\ngroup by k.kpi_name, k.kpi_country_id, IF(k.kpi_month=-1,0,k.kpi_month)\r\norder by kpi_month"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time_sec,\n  r.restriction_message as metric,\n  count(r.restriction_id) as value\nfrom warning w\ninner join layer l on w.warning_layer_id=l.layer_id\ninner join plan_layer pl on pl.plan_layer_layer_id=l.layer_id\ninner join plan p on p.plan_id=pl.plan_layer_plan_id and p.plan_state != 'DELETED'\ninner join country c on c.country_id=p.plan_country_id\ninner join restriction r on w.warning_restriction_id=r.restriction_id\nwhere w.warning_active=1 and warning_issue_type='Error' and c.country_name IN ($Team)\ngroup by r.restriction_message\norder by value DESC"
    }
   ]
  }
 ]
}