# Enabled in Symfony 7 by default:
#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

when@dev:
  _tools:
    resource: 'routes/tools.yaml'
    prefix: '/_tools'
