name: php

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: MSPChallenge-Server
      - name: run linters
        run: cd MSPChallenge-Server && ./test.sh && vendor/bin/phpstan analyse
