name: php

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']
    steps:
      - uses: actions/checkout@v2
      - name: run linters
        run: ./test.sh
