name: php

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
    steps:
      - uses: actions/checkout@v3
      - name: Install composer dependencies
        run: bash install.sh
      - name: Run our test script with cs fixer
        run: cd MSPChallenge-Server && ./test.sh && ./vendor/bin/phpstan
