name: php

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - uses: actions/checkout@v3
      - name: Install composer dependencies
        run: bash install.sh
      - name: Phpstan analyse
        run: vendor/bin/phpstan analyse --memory-limit=-1
      - name: Run our own custom linter script
        run: bash test.sh

